class Url:
    MAIN_URL = 'https://qa-scooter.praktikum-services.ru/'
    CREATING_COURIER = '/api/v1/courier'
    COURIER_LOGIN = '/api/v1/courier/login'
    COURIER_DELETE = '/api/v1/courier/'
    GET_ORDER_LIST = '/api/v1/orders'
    POST_CREATING_ORDER = '/api/v1/orders'
    Get_ORDER_BY_NUMBER = '/api/v1/orders/track'
    ORDER_CANCEL = '/api/v1/orders/cancel'
    ORDER_ACCEPT = '/api/v1/orders/accept/'